api_platform:
  title: Pengajuan Api
  version: 1.0.0
  defaults:
    stateless: true
    cache_headers:
      vary: [ 'Content-Type', 'Authorization', 'Origin', 'X-TIMESTAMP', 'X-SIGNATURE' ]
  formats:
    jsonld: [ "application/ld+json" ]
    #        jsonhal: ["application/hal+json"]
    #        jsonapi: ["application/vnd.api+json"]
    json: [ "application/json" ]
    multipart: [ 'multipart/form-data' ]
