# config/packages/vich_uploader.yaml or app/config/config.yml
vich_uploader:
  db_driver: orm
  mappings:
    docs:
      uri_prefix: /uploads/files
      upload_destination: '%kernel.project_dir%/public/uploads/files'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

    pengajuan_attachment:
      uri_prefix: /uploads/pengajuan_attachment
      upload_destination: '%kernel.project_dir%/public/uploads/pengajuan_attachment'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

