<?php

// This file was generated by running "composer dump-env prod"

return array (
  'APP_ENV' => 'prod',
  'APP_SECRET' => '5fdea0b7929fa9ca474e8c6df6fe7e4e',
  'DATABASE_URL' => 'mysql://kemenag:kemenaG@123@127.0.0.1:3306/kemenag_db?serverVersion=8.0.42&charset=utf8mb4',
  'CORS_ALLOW_ORIGIN' => '^https?:\/\/([a-z0-9-]+\.)*gaspul\.com$',
);
